name: home_widget_vconnex
description: A plugin to provide a common interface for creating HomeScreen Widgets for Android and iOS by Vconnex.
version: 0.1.5
repository: https://github.com/ABausG/home_widget

environment:
  sdk: '>=2.12.13 <4.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  path_provider_foundation: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.1
  # golden_toolkit: ^0.15.0
  mocktail: ^1.0.0
  path_provider_platform_interface:
  plugin_platform_interface:

flutter:
  plugin:
    platforms:
      android:
        package: es.antonborri.home_widget
        pluginClass: HomeWidgetPlugin
      ios:
        pluginClass: HomeWidgetPluginVconex
